version: "3.5"

services:
  cardano-node-ogmios:
    image: cardanosolutions/cardano-node-ogmios:v4.0.0-beta.4-${NETWORK:-mainnet}
    logging:
      driver: "json-file"
      options:
        max-size: "400k"
        max-file: "20"
    ports:
      - ${OGMIOS_PORT:-1337}:1337
    restart: on-failure
    volumes:
      - node-db:/db

  payment-notifier:
    build:
      context: ../..
      target: payment-notifier
    depends_on:
      - cardano-node-ogmios
    restart: always
    environment:
      - API_PORT=${API_PORT:-3000}
      - OGMIOS_HOST=cardano-node-ogmios
      - OGMIOS_PORT=1337
      - PUSHOVER_TOKEN_FILE=/run/secrets/pushover_token
      - PUSHOVER_USER_FILE=/run/secrets/pushover_user
    ports:
      - ${API_PORT:-3000}:3000
    secrets:
      - pushover_token
      - pushover_user

secrets:
  pushover_token:
    file: ./secrets/pushover_token
  pushover_user:
    file: ./secrets/pushover_user
volumes:
  node-db:
